language: node_js

node_js:
  - "iojs"

branches:
  only:
    - "master"

before_script:
  - npm install -g karma karma-cli bower
  - bower install
  - npm install

email:
  on_failure: change
  on_success: never
